"""Public API for the model-free adaptive temporal-search core."""

from .algorithms import (
    adjacent_hinge_penalty,
    assemble_ordered_tuples,
    calibrate_frame_scores,
    cluster_temporal_regions,
    generate_boundary_proposals,
    merge_overlapping_regions,
    pairwise_softmax,
    prioritize_videos,
    robust_sigmoid,
    select_refinement_frontier,
    temporal_nms,
)
from .proposal_profiles import generate_profiled_proposals
from .retrieval import fuse_candidates_rrf
from .models import (
    AdjacentGapConstraint,
    BoundaryHyperparameters,
    ClusteringHyperparameters,
    EventConstraint,
    EventDefinition,
    EventProposal,
    FrameScoreSample,
    ModelRuntimeSpec,
    RankingHyperparameters,
    RefinementHyperparameters,
    RetrievalHyperparameters,
    SearchConstraints,
    SearchHyperparameters,
    SparseCandidate,
    TemporalRegion,
    TupleResult,
    VideoPriority,
)

__all__ = [
    "AdjacentGapConstraint",
    "BoundaryHyperparameters",
    "ClusteringHyperparameters",
    "EventConstraint",
    "EventDefinition",
    "EventProposal",
    "FrameScoreSample",
    "ModelRuntimeSpec",
    "RankingHyperparameters",
    "RefinementHyperparameters",
    "RetrievalHyperparameters",
    "SearchConstraints",
    "SearchHyperparameters",
    "SparseCandidate",
    "TemporalRegion",
    "TupleResult",
    "VideoPriority",
    "adjacent_hinge_penalty",
    "assemble_ordered_tuples",
    "calibrate_frame_scores",
    "cluster_temporal_regions",
    "generate_boundary_proposals",
    "generate_profiled_proposals",
    "fuse_candidates_rrf",
    "merge_overlapping_regions",
    "pairwise_softmax",
    "prioritize_videos",
    "robust_sigmoid",
    "select_refinement_frontier",
    "temporal_nms",
]
